version: '2.1'
orbs:
  mabl-trigger-tests: mabl/trigger-tests@1.0.6
jobs:
  run-mabl-tests:
    machine: true
    steps:
      - mabl-trigger-tests/run-tests:
          api-key: RgYhOfX3bSVXo8VweVZ7GQ
          browsers: chrome
          environment-id: niIn0o7r5dqEA4GdaK2hGQ-e 
          mabl-branch: main
workflows:
  test-my-app:
    jobs:
      - run-mabl-tests
